spring.application.name=spac-core-service
server.port=8081

# PostgreSQL
spring.datasource.url=urs 
spring.datasource.username=postgres
spring.datasource.password=urs password plx
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Using 'validate' avoids index-already-exists errors
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=spac-group

# Temporal Connection (Required if running locally)
temporal.service.address=localhost:7233
temporal.namespace=default
