spring.application.name=spac-core-service
server.port=${PORT:8081}

# PostgreSQL (Railway Cloud)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka (Aiven Cloud Configuration)
spring.kafka.bootstrap-servers=spac-kafka-dev-spac-simulator-dev.c.aivencloud.com:13249
spring.kafka.consumer.group-id=spac-group
spring.kafka.properties.security.protocol=SSL

# Kafka SSL Security Settings (Using classpath for cloud deployment)
spring.kafka.properties.ssl.truststore.location=classpath:certs/client.truststore.jks
spring.kafka.properties.ssl.truststore.password=${KAFKA_PASSWORD}
spring.kafka.properties.ssl.truststore.type=JKS

spring.kafka.properties.ssl.keystore.location=classpath:certs/client.keystore.p12
spring.kafka.properties.ssl.keystore.password=${KAFKA_PASSWORD}
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.key.password=${KAFKA_PASSWORD}

# Temporal Connection
temporal.service.address=${TEMPORAL_ADDRESS:localhost:7233}
temporal.namespace=default