spring.application.name=spac-core-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/spac_db
spring.datasource.username=postgres
spring.datasource.password=Gauravpt@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Kafka (Aiven Cloud Configuration)
spring.kafka.bootstrap-servers=spac-kafka-dev-spac-simulator-dev.c.aivencloud.com:13249
spring.kafka.consumer.group-id=spac-group
spring.kafka.properties.security.protocol=SSL

# Kafka SSL Security Settings (MUST match your Simulation Engine)
spring.kafka.properties.ssl.truststore.location=C:/Users/gaura/OneDrive/Desktop/SPAC/spac-core-service/src/main/resources/certs/client.truststore.jks
spring.kafka.properties.ssl.truststore.password=Gauravpt@123
spring.kafka.properties.ssl.truststore.type=JKS

spring.kafka.properties.ssl.keystore.location=C:/Users/gaura/OneDrive/Desktop/SPAC/spac-core-service/src/main/resources/certs/client.keystore.p12
spring.kafka.properties.ssl.keystore.password=Gauravpt@123
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.key.password=Gauravpt@123

# Temporal Connection
temporal.service.address=localhost:7233
temporal.namespace=default